# Generated by Django 4.0.1 on 2022-01-24 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('email', models.CharField(max_length=100, verbose_name='Employee Email')),
                ('address', models.CharField(max_length=300, verbose_name='Employee Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Employee Phone')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Employee Salary')),
                ('photo', models.FileField(blank=True, default='employee/blank.jpg', upload_to='employee', verbose_name='Employee Photo')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.department')),
            ],
        ),
    ]
